import Nav from "./components/Nav";
import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  icon: "https://i.imgur.com/LFh8Kdi.png",
  title: "Sanyam Singh",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth  overflow-x-hidden ">
      <link rel="icon" href="https://i.imgur.com/LFh8Kdi.png" />
      <body className={inter.className}>
        <Providers>
          <Nav />

          {children}
        </Providers>
      </body>
    </html>
  );
}
